orbs:
 docker: circleci/docker@1.5.0
version: 2.1
executors:
 docker-publisher: 
 environment:
 IMAGE_NAME: abebewoldetsadik/simple_node
 docker: 
 — image: circleci/node:latest
 auth:
 username: $DOCKER_USERNAME
 password: $DOCKER_PASSWORD
jobs:
 publishLatestToHub: 
 executor: docker-publisher
 
 steps: 
 — checkout
 — setup_remote_docker
 — run: 
 name: Publish Docker Image to Docker Hub
 command: |
 echo “$DOCKER_PASSWORD” | docker login -u “$DOCKER_USERNAME” — password-stdin
 docker build -t $IMAGE_NAME .
 docker push $IMAGE_NAME:latest
workflows:
 version: 2
 build-master:
 jobs:
 — publishLatestToHub
